# gitleaks.toml
title = "Shyft gitleaks config"

[[rules]]
id = "firebase-admin-b64"
description = "Firebase Admin key (base64 JSON)"
regex = '''FIREBASE_SERVICE_ACCOUNT_B64\s*=\s*[A-Za-z0-9+/_-]{80,}={0,2}'''
entropy = 3.5
tags = ["key","firebase","admin"]

[[rules]]
id = "gemini-api-key"
description = "Gemini API key"
regex = '''GEMINI_API_KEY\s*=\s*[A-Za-z0-9_\-]{20,}'''
tags = ["key","gemini","google"]

[[rules]]
id = "jwt-secret"
description = "JWT secret"
regex = '''JWT_SECRET\s*=\s*[A-Za-z0-9._\-]{32,}'''
tags = ["secret","jwt"]

[[rules]]
id = "session-secret"
description = "Session secret"
regex = '''SESSION_SECRET\s*=\s*[A-Za-z0-9._\-]{32,}'''
tags = ["secret","session"]

[[rules]]
id = "nextauth-secret"
description = "NextAuth secret"
regex = '''NEXTAUTH_SECRET\s*=\s*[A-Za-z0-9._\-]{16,}'''
tags = ["secret","nextauth"]

# Reduce false positives in CSS/config text fragments you'd shown earlier
[[allowlist]]
description = "Allow common config text fragments"
regexes = [
  '''Name of Subreddit to watch''',
  '''reddit\.com/r/''',
]

