name: Secret Scan (detect-secrets)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: pip install detect-secrets==1.5.0

      - name: Ensure baseline exists (generate if missing)
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "No baseline found. Generating a redacted baseline artifact (CI will fail until you commit it)."
            detect-secrets scan --all-files > .secrets.baseline
          fi

      - name: Audit against baseline
        run: |
          detect-secrets audit --report --json .secrets.baseline || true
          detect-secrets scan --baseline .secrets.baseline --all-files
