# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ---------- Client ----------
      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

      # ---------- Server ----------
      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Type-check server
        working-directory: server
        run: npx tsc --noEmit

      - name: Build server (tsc → dist/)
        working-directory: server
        run: npx tsc

      # Smoke import compiled server entry to ensure ESM deps resolve.
      # We pass dummy env to avoid real Firebase/Admin initialization.
      - name: Smoke import server (compiled JS)
        working-directory: server
        env:
          NODE_ENV: ci
          FIREBASE_SERVICE_ACCOUNT_JSON: '{"type":"service_account","project_id":"dummy","private_key_id":"x","private_key":"-----BEGIN PRIVATE KEY-----\nMIIB\n-----END PRIVATE KEY-----\n","client_email":"dummy@dummy.iam.gserviceaccount.com","client_id":"0","token_uri":"https://oauth2.googleapis.com/token"}'
          FIREBASE_STORAGE_BUCKET: dummy.appspot.com
        run: |
          node -e "import('./dist/index.js').then(()=>console.log('ok')).catch(e=>{console.error(e);process.exit(1)})"
