name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Client build
      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

      # Server type-check + smoke boot
      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Type-check server
        working-directory: server
        run: npx tsc --noEmit

      # Optional: ensure index imports resolve (no secrets needed)
      - name: Smoke import server
        working-directory: server
        env:
          # Provide dummy env so dotenv loads but Firebase isn't initialized
          FIREBASE_SERVICE_ACCOUNT_JSON: '{"type":"service_account","project_id":"dummy","private_key_id":"x","private_key":"-----BEGIN PRIVATE KEY-----\nMIIB\n-----END PRIVATE KEY-----\n","client_email":"dummy@dummy.iam.gserviceaccount.com","client_id":"0","token_uri":"https://oauth2.googleapis.com/token"}'
          FIREBASE_STORAGE_BUCKET: dummy.appspot.com
        run: |
          node -e "import('./src/index.ts').then(()=>console.log('ok')).catch(e=>{console.error(e);process.exit(1)})"
