name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - chore/create-parsing-backlog   # <-- change if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      # Wrangler picks this up automatically if provided
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      # API token needs “Workers:Edit”, “Pages:Edit” (not used), and “Workers KV/Sec/Routes” if applicable
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (Next → .vercel/output + _worker.js)
        run: npm run cf:build

      - name: Deploy (wrangler)
        run: npm run cf:deploy
