name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "server/**"
      - "wrangler.toml"
      - ".github/workflows/cloudflare.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' && secrets.CLOUDFLARE_ACCOUNT_ID != '' }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Build server (if needed)
        working-directory: server
        run: |
          if npm run | grep -qE "^ *build"; then npm run build; else echo "no server build"; fi

      - name: Publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Adjust --name / --env if your wrangler.toml defines them
          wrangler publish
