# .github/workflows/docs.yml
name: CI + Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install root dependencies (required for workspace commands and docs generation)
      - name: Install root dependencies
        run: npm ci

      # ---------- Web App Build Verification ----------
      # Build web app as a sanity check to ensure the build process works before generating docs
      - name: Install web app dependencies
        run: npm --workspace=@ryne/web ci

      - name: Build web app (sanity check)
        run: npm --workspace=@ryne/web run build

      # ---------- API Type Checking ----------
      # Ensure API code is type-safe before generating documentation
      - name: Install API dependencies
        run: npm --workspace=@ryne/api ci

      # Install missing type definitions required for proper TypeScript compilation
      - name: Install API type definitions
        run: npm --workspace=@ryne/api install @types/cors

      - name: Type-check API
        run: npm --workspace=@ryne/api exec tsc -- --noEmit

      # ---------- Documentation Generation ----------
      # Generate TypeDoc documentation for both web and API codebases
      # Generate OpenAPI/Redoc documentation from openapi.yaml
      # Create unified documentation site with index page
      - name: Build comprehensive documentation
        run: npm run docs

      # ---------- GitHub Pages Deployment ----------
      # Only deploy documentation on pushes to main branch (not on PRs)
      - name: Setup GitHub Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v5

      - name: Upload documentation artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4
