# .github/workflows/firebase-deploy.yml
name: Firebase Deploy

on:
  push:
    branches: ["norris"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Write Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_B64 }}" | base64 -d > sa.json
          echo "Wrote sa.json"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Auth with service account
        run: |
          gcloud auth activate-service-account "${{ secrets.FIREBASE_SA_EMAIL }}" \
            --key-file=sa.json
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Firebase deploy
        run: firebase deploy --non-interactive
