# .github/workflows/secret-scan.yml
name: Secret Scan (gitleaks)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --source . --no-banner --config gitleaks.toml
